<a href="https://colab.research.google.com/github/seohg5138-gif/goya_task/blob/main/4%EC%A3%BC%EC%B0%A8%EB%B3%B5%EC%8A%B5_%ED%81%AC%EB%A1%A4%EB%9F%AC.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import gdown
gdown.download("https://bit.ly/3eecMKZ", '남산도서관 장서 대출목록 (2021년 04월).csv', quiet=False)

Downloading...
From: https://bit.ly/3eecMKZ
To: /content/남산도서관 장서 대출목록 (2021년 04월).csv
100%|██████████| 58.1M/58.1M [00:01<00:00, 41.7MB/s]

'남산도서관 장서 대출목록 (2021년 04월).csv'

In [2]:
import chardet
with open('남산도서관 장서 대출목록 (2021년 04월).csv', mode='rb') as f:
  d=f.readline()

print(chardet.detect(d))

{'encoding': 'EUC-KR', 'confidence': 0.99, 'language': 'Korean'}

In [3]:
with open('남산도서관 장서 대출목록 (2021년 04월).csv', encoding='EUC-KR') as f:
  print(f.readline())
  print(f.readline())

번호,도서명,저자,출판사,발행년도,ISBN,세트 ISBN,부가기호,권,주제분류번호,도서권수,대출건수,등록일자,

"1","인공지능과 흙","김동훈 지음","민음사","2021","9788937444319","","","","","1","0","2021-03-19",

#데이터프레임 다루기: 판다스

In [4]:
import pandas as pd
df=pd.read_csv('남산도서관 장서 대출목록 (2021년 04월).csv', encoding='EUC-KR')

/tmp/ipykernel_5847/3422748757.py:2: DtypeWarning: Columns (5,6,9) have mixed types. Specify dtype option on import or set low_memory=False.
  df=pd.read_csv('남산도서관 장서 대출목록 (2021년 04월).csv', encoding='EUC-KR')

In [5]:
df.head()

,번호,도서명,저자,출판사,발행년도,ISBN,세트 ISBN,부가기호,권,주제분류번호,도서권수,대출건수,등록일자,Unnamed: 13
0,1,인공지능과 흙,김동훈 지음,민음사,2021,9788937444319,NaN,NaN,NaN,NaN,1,0,2021-03-19,NaN
1,2,가짜 행복 권하는 사회,김태형 지음,갈매나무,2021,9791190123969,NaN,NaN,NaN,NaN,1,0,2021-03-19,NaN
2,3,나도 한 문장 잘 쓰면 바랄 게 없겠네,김선영 지음,블랙피쉬,2021,9788968332982,NaN,NaN,NaN,NaN,1,0,2021-03-19,NaN
3,4,예루살렘 해변,"이도 게펜 지음, 임재희 옮김",문학세계사,2021,9788970759906,NaN,NaN,NaN,NaN,1,0,2021-03-19,NaN
4,5,김성곤의 중국한시기행 : 장강·황하 편,김성곤 지음,김영사,2021,9788934990833,NaN,NaN,NaN,NaN,1,0,2021-03-19,NaN

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 401682 entries, 0 to 401681
Data columns (total 14 columns):
 #   Column       Non-Null Count   Dtype
---  ------       --------------   -----
 0   번호           401682 non-null  int64
 1   도서명          401279 non-null  object
 2   저자           401481 non-null  object
 3   출판사          396887 non-null  object
 4   발행년도         401665 non-null  object
 5   ISBN         401682 non-null  object
 6   세트 ISBN      61871 non-null   object
 7   부가기호         325034 non-null  object
 8   권            68267 non-null   object
 9   주제분류번호       381360 non-null  object
 10  도서권수         401682 non-null  int64
 11  대출건수         401682 non-null  int64
 12  등록일자         401682 non-null  object
 13  Unnamed: 13  0 non-null       float64
dtypes: float64(1), int64(3), object(10)
memory usage: 42.9+ MB

In [7]:
import pandas as pd
df=pd.read_csv('남산도서관 장서 대출목록 (2021년 04월).csv', encoding='EUC-KR',low_memory=False)

In [8]:
df.to_csv('ns202104.csv')

In [9]:
#for i in range() 이거 기분적인 공식이다.
with open('ns202104.csv') as f:
  for i in range(10):
    print(f.readline(), end='')

,번호,도서명,저자,출판사,발행년도,ISBN,세트 ISBN,부가기호,권,주제분류번호,도서권수,대출건수,등록일자,Unnamed: 13
0,1,인공지능과 흙,김동훈 지음,민음사,2021,9788937444319,,,,,1,0,2021-03-19,
1,2,가짜 행복 권하는 사회,김태형 지음,갈매나무,2021,9791190123969,,,,,1,0,2021-03-19,
2,3,나도 한 문장 잘 쓰면 바랄 게 없겠네,김선영 지음,블랙피쉬,2021,9788968332982,,,,,1,0,2021-03-19,
3,4,예루살렘 해변,"이도 게펜 지음, 임재희 옮김",문학세계사,2021,9788970759906,,,,,1,0,2021-03-19,
4,5,김성곤의 중국한시기행 : 장강·황하 편,김성곤 지음,김영사,2021,9788934990833,,,,,1,0,2021-03-19,
5,6,처음 읽는 음식의 세계사,"미야자키 마사카츠 지음, 한세희 옮김",탐나는책,2021,9791189550370,,,,,1,0,2021-03-19,
6,7,아르센 벵거 자서전 My Life in Red and White,"아르센 벵거 지음, 이성모 옮김",한즈미디어(한스미디어),2021,9791160075793,,,,,1,0,2021-03-19,
7,8,쓰고 달콤한 직업,천운영 지음,마음산책,2021,9788960906679,,,,,1,0,2021-03-19,
8,9,일잘러의 노션 100% 활용법,제레미 강 지음,위키북스,2021,9791158392512,,,,,1,0,2021-03-19,

In [10]:
ns_df=pd.read_csv('ns202104.csv', low_memory=False)
ns_df.head()

,Unnamed: 0,번호,도서명,저자,출판사,발행년도,ISBN,세트 ISBN,부가기호,권,주제분류번호,도서권수,대출건수,등록일자,Unnamed: 13
0,0,1,인공지능과 흙,김동훈 지음,민음사,2021,9788937444319,NaN,NaN,NaN,NaN,1,0,2021-03-19,NaN
1,1,2,가짜 행복 권하는 사회,김태형 지음,갈매나무,2021,9791190123969,NaN,NaN,NaN,NaN,1,0,2021-03-19,NaN
2,2,3,나도 한 문장 잘 쓰면 바랄 게 없겠네,김선영 지음,블랙피쉬,2021,9788968332982,NaN,NaN,NaN,NaN,1,0,2021-03-19,NaN
3,3,4,예루살렘 해변,"이도 게펜 지음, 임재희 옮김",문학세계사,2021,9788970759906,NaN,NaN,NaN,NaN,1,0,2021-03-19,NaN
4,4,5,김성곤의 중국한시기행 : 장강·황하 편,김성곤 지음,김영사,2021,9788934990833,NaN,NaN,NaN,NaN,1,0,2021-03-19,NaN

In [11]:
#index_col이거 중요하다
#csv파일에 인덱스가 이미 있다는 것을 알려주려면 index_col 매개변수를 사용해야 한다.
ns_df=pd.read_csv('ns202104.csv',index_col=0, low_memory=False)
ns_df.head()

,번호,도서명,저자,출판사,발행년도,ISBN,세트 ISBN,부가기호,권,주제분류번호,도서권수,대출건수,등록일자,Unnamed: 13
0,1,인공지능과 흙,김동훈 지음,민음사,2021,9788937444319,NaN,NaN,NaN,NaN,1,0,2021-03-19,NaN
1,2,가짜 행복 권하는 사회,김태형 지음,갈매나무,2021,9791190123969,NaN,NaN,NaN,NaN,1,0,2021-03-19,NaN
2,3,나도 한 문장 잘 쓰면 바랄 게 없겠네,김선영 지음,블랙피쉬,2021,9788968332982,NaN,NaN,NaN,NaN,1,0,2021-03-19,NaN
3,4,예루살렘 해변,"이도 게펜 지음, 임재희 옮김",문학세계사,2021,9788970759906,NaN,NaN,NaN,NaN,1,0,2021-03-19,NaN
4,5,김성곤의 중국한시기행 : 장강·황하 편,김성곤 지음,김영사,2021,9788934990833,NaN,NaN,NaN,NaN,1,0,2021-03-19,NaN

In [12]:
#애초에 데이터프레임을 csv파일로 저장할때 인덱스를 빼고 저장할 수 있다. 이렇게 하려면 to_csv()메서드에 index매개변수를 False로 지정!
df.to_csv('ns202104.csv', index=False)

## 파이썬에서 JSON 데이터 다루기

In [13]:
d={'name':'혼자 공부하는 데이터 분석'}
print(d['name'])
print(d)

혼자 공부하는 데이터 분석
{'name': '혼자 공부하는 데이터 분석'}

In [14]:
import json
d_str = json.dumps(d, ensure_ascii=False)
print(d_str)
print(type(d_str))

{"name": "혼자 공부하는 데이터 분석"}
<class 'str'>

웹 기반 api가 사용하는 http프로토콜이 텍스트 기반이기 때문! 웹브라우져에서 HTML소스를 보았을 때 텍스트로 출력되었던 것을 기억하시죠?
그래서 HTTPS 프로토콜 데이터를 전송하려면 먼체 객체를 텍스트로 변환해야 합니다.
이렇게 프로그램 상의 객체를 저장하거나 읽을 있는 형태로 변환하는 것을 직렬화라고 합니다.
반대로 직렬화(serialization)된 정보를 다시 프로그램에서 실행 가능한 객체로 변환하는 것을 역직렬화(dsserialization) 라고 합니다.

In [15]:
d2=json.loads(d_str)
print(d2['name'])
print(type(d2))

혼자 공부하는 데이터 분석
<class 'dict'>

In [16]:
d3=json.loads('{"name":"혼자 공부하는 데이터 분석", "author":"박해선","year":2022}')
print(d3['name'])
print(d3['author'])
print(d3['year'])

혼자 공부하는 데이터 분석
박해선
2022

In [17]:
d3=json.loads('{"name":"혼자 공부하는 데이터 분석", "author":["박해선","홍길동"],"year":2022}')
print(d3['author'][1])

홍길동

In [18]:
d4_str = """
[{"name":"혼자 공부하는 데이터 분석", "author":"박해선", "year":2022},
{"name":"혼자 공부하는 데이터 분석+딥러닝", "author":"박해선", "year":2020}
]"""

d4 = json.loads(d4_str)
print(d4[0]["name"])
print(d4[0])
print(d4[1])

혼자 공부하는 데이터 분석
{'name': '혼자 공부하는 데이터 분석', 'author': '박해선', 'year': 2022}
{'name': '혼자 공부하는 데이터 분석+딥러닝', 'author': '박해선', 'year': 2020}

In [19]:
import pandas as pd
pd.read_json(d4_str)

/tmp/ipykernel_5847/1308304786.py:2: FutureWarning: Passing literal json to 'read_json' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  pd.read_json(d4_str)

                 name author  year
0      혼자 공부하는 데이터 분석    박해선  2022
1  혼자 공부하는 데이터 분석+딥러닝    박해선  2020

In [20]:
pd.DataFrame(d4)

                 name author  year
0      혼자 공부하는 데이터 분석    박해선  2022
1  혼자 공부하는 데이터 분석+딥러닝    박해선  2020

In [21]:
from io import StringIO
import pandas as pd
pd.read_json(StringIO(d4_str))

                 name author  year
0      혼자 공부하는 데이터 분석    박해선  2022
1  혼자 공부하는 데이터 분석+딥러닝    박해선  2020

##파이썬에서 XML데이터 다루기

In [22]:
#XML문자열을 파이썬 객체로 변환하기:fromstring()함수
x_str = """
<book>
  <name>혼자 공부하는 데이터 분석</name>
  <author>박해선</author>
  <year>2022</year>
</book>
"""

import xml.etree.ElementTree as et
book=et.fromstring(x_str)
print(type(book))
print((book.tag))

<class 'xml.etree.ElementTree.Element'>
book

In [23]:
#자식 엘리먼트 확인하기:findtext()메서드
book_childs = list(book)
print(book_childs)

[<Element 'name' at 0x7b46f006a160>, <Element 'author' at 0x7b46f006a1b0>, <Element 'year' at 0x7b46f006a250>]

In [24]:
name,author, year = book_childs
print(name.text)
print(author.text)
print(year.text)

혼자 공부하는 데이터 분석
박해선
2022

XML은 자식 엘리먼트순서가 항상 일정하다는 것을 보장 하지 않는다. book객체의 findtext()메서드를 사용하면 해당하는 자식 엘리먼트를 탐색하여 자동으로 텍스트를 반환!

In [25]:
name = book.findtext('name')
author = book.findtext('author')
year = book.findtext('year')
print(name)
print(author)
print(year)

혼자 공부하는 데이터 분석
박해선
2022

In [26]:
x2_str = """
<books>
  <book>
    <name>혼자 공부하는 데이터 분석</name>
    <author>박해선</author>
    <year>2022</year>
  </book>
  <book>
    <name>혼자 공부하는 데이터 분석+딥러닝</name>
    <author>박해선</author>
    <year>2020</year>
  </book>
</books>
"""
books=et.fromstring(x2_str)
print(books.tag)

books

###여러개의 자식 엘리먼트 확인하기:findall()메서드와 for문

In [27]:
for book in books.findall('book'):
  name = book.findtext('name')
  author = book.findtext('author')
  year = book.findtext('year')
  print(name)
  print(author)
  print(year)
  print()

혼자 공부하는 데이터 분석
박해선
2022

혼자 공부하는 데이터 분석+딥러닝
박해선
2020

##JSON처럼 XML을 바로 판다스로 바꾸는 방법

pd.read_xml(StringIO(x2_str))